config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'
  resources :cars
  resources :werbhooks ,only: [:create]

  get 'business/index', as: :business
  devise_for :users
  devise_for :clients, path: 'clients'
  get 'search' => 'home#search', as: :search
  post'book'=>'home#book',as: :book
  post 'booking'=>'home#create', as: :booking
  get 'invoice'=>'profile#invoice', as: :invoice
  get 'customer'=>'customer#index', as: :customer
  get 'states'=>'home#index'




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_action :authenticate_user!, only: %i[ book ]
   before_action :book_params,only: %i[ create ]
	# before_action :check_signed_in
def index
  @search= User.ransack (params[:q])
  @searchs = @search.result(distink: true)
  @car = Car.limit(4)

end

def search
  @search= User.ransack (params[:q])
  @search= Car.ransack (params[:q])
  @searchs = @search.result(distink: true)
  @car_caryears_cont = ['2021']
  @car_carmakes_cont = ['Audi']
  @car_carmodels_cont = ['233']
end



def book
    @from = params[:dateform]
    @to = params[:dateto]
    @totalDays = (@to.to_date - @from.to_date).to_i
    @price = params[:price].to_i
    @totalPrice = (@price * @totalDays)
    if @totalPrice  < 1
       @totalPrice = @price
     else
        @totalPrice
    end
    @car = Car.find(params[:id])
    @book = Book.new

end

def create
  @book = Book.new(book_params)
  payment_intent = Stripe::PaymentIntent.create({
  customer: current_user.strip_cutomer_id,
  amount: @book.price ,
  currency: 'usd',
})
 # render json:
 @card = payment_intent.payment_method_types
 @payment_intent_confirm = Stripe::PaymentIntent.confirm(
  payment_intent.id,
  {payment_method: 'pm_card_visa'}
)
 if @payment_intent_confirm
  @book.stripe_payment_id = payment_intent.id
  respond_to do |format|
   if @book.save
       format.html { redirect_to invoice_path, notice: "Car was successfully created." }
   else
       format.html { render json: @book.errors, status: :unprocessable_entity }

   end
  end
 else
    render json: payment_intent
 end

  # @car = Car.find(params[:id])
  # @user =current_user.strip_cutomer_id
  # @session = Stripe::Checkout::Session.create({
  #   customer: current_user.strip_cutomer_id,
  #   client_reference_id: params[:client_id],
  #   payment_method_types: ['card'],
  #   line_items: [{
  #   name:@car.carmakes,
  #   amount:params[:total],
  #   currency:"usd",
  #   quantity:params[:day],
  #   }],
  #   mode: 'payment',
  #   success_url: 'http://localhost:3000/invoice',
  #   cancel_url: 'http://localhost:3000/',
  #   });
  #
  #   redirect_to @session.url

end

# def check_signed_in
#   redirect_to business_path if user_signed_in?
# end
private

def book_params
  params.require(:book).permit(:price, :name, :number, :car_id, :user_id,:stripe_payment_id,:status,:dateFrom,:dateTo,:totalPrice)
end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_featuer.html.erb
<!--Card 1-->
<div class="py-12 bg-white xl:mt-40">
  <div class=" mx-auto px-4 sm:px-6 lg:px-8">
    <div class="lg:text-center my-14">

      <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
        Find the perfect car
      </p>
      <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">
        Go prepared in a rugged 4x4 to take on winter roads with ease, or a camper van to take you to the trees.
      </p>
    </div>
    <div class=" grid grid-cols-5 sm:grid-cols-1 md:grid-cols-5 lg:grid-cols-5 xl:grid-cols-4 gap-1  h-3/5">
      <%  @car.each do |car| %>
        <div class="w9/12 h-5/5 rounded overflow-hidden shadow-lg">
          <%= image_tag car.image.url ,class:"w-full h-3/7 p-4"%>
          <div class="h-4/6">
            <div class="px-6 py-2">
              <div class="font-bold text-xl mb-2"><%= car.carmakes %></div>
            </div>
            <div class="px-5 flex">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2 "><%= car.carmodels %></span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2 "><%= car.caryears %></span>
            </div>
            <hr>
            <div class="px-5 mt-2 block">
              <span class="inline-block px-1 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2 "><%= car.user.companyname %></span>
              <span class="inline-block px-1 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2 "><%= car.user.country_cont %>,
                <%= car.user.state_cont %></span>
            </div>
            <hr>
            <div class="px-5 mt-2">
              <button
                type="submit"
                class="float-right group relative w-20 mb-2  py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                More
              </button>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="flex flex-col justify-center items-center my-5">
      <button
        type="submit"
        class="items-center group relative w-20   py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        <span class="absolute left-0 inset-y-0 flex items-center pl-3"></span>
        Book
      </button>
    </div>
  </div>

app/views/home/_header.html.erb
<div>
  <div class="relative pt-6 px-4 sm:px-6 lg:px-8">
    <nav class="relative flex items-center justify-between sm:h-10 lg:justify-start" aria-label="Global">
      <div class="flex items-center flex-grow flex-shrink-0 lg:flex-grow-0">
        <div class="flex items-center justify-between w-full md:w-auto">
          <a href="#">
            <span class="sr-only">Workflow</span>
            <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg">
          </a>
          <div class="-mr-2 flex items-center md:hidden">
            <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <!-- Heroicon name: outline/menu -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
              </svg>
            </button>
          </div>
        </div>
      </div>
      <div class="hidden md:block md:ml-10 md:pr-4 md:space-x-8">
        <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Product</a>

        <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Features</a>

        <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Marketplace</a>
        <% if client_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, class:"font-medium text-indigo-600 hover:text-indigo-500", method: :delete %>
        <% elsif user_signed_in? %>
        <%= link_to "Partner" ,client_session_path,class:"font-medium text-indigo-600 hover:text-indigo-500"%>
        <% else %>
        <%= link_to "Partner" ,client_session_path,class:"font-medium text-indigo-600 hover:text-indigo-500"%>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, class:"font-medium text-indigo-600 hover:text-indigo-500", method: :delete %>
        <%  else %>
          <%= link_to "Log in" ,user_session_path,class:"font-medium text-indigo-600 hover:text-indigo-500"%>
        <% end %>
      </div>
    </nav>
  </div>

  <!-- Mobile menu, show/hide based on menu open state. Entering: "duration-150 ease-out" From: "opacity-0 scale-95" To: "opacity-100 scale-100" Leaving: "duration-100 ease-in" From: "opacity-100 scale-100" To: "opacity-0 scale-95" -->
  <div class="absolute z-10 top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
    <div class="rounded-lg shadow-md bg-white ring-1 ring-black ring-opacity-5 overflow-hidden">
      <div class="px-5 pt-4 flex items-center justify-between">
        <div>
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="">
        </div>
        <div class="-mr-2">
          <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
            <span class="sr-only">Close main menu</span>
            <!-- Heroicon name: outline/x -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>
      </div>
      <div class="px-2 pt-2 pb-3 space-y-1">
        <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Product</a>

        <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Features</a>

        <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Marketplace</a>

        <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Company</a>
      </div>
      <a href="#" class="block w-full px-5 py-3 text-center font-medium text-indigo-600 bg-gray-50 hover:bg-gray-100">
        Register your company
      </a>
    </div>
  </div>
</div>
</div>

app/views/home/_payment_form.html.erb
<h3 class="pt-5 mb-4">Payment</h3>
  <div class="mb-6 relative mt-2">
    <label for="card-element" class="label">
      Enter credit or debit card. All sessions cost $199 USD.
    </label>

    <div id="card-element" class="input">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

app/views/home/book.html.erb
<%= render 'header' %>
<br>
<div class="container mx-auto mt-5 ">
  <div class="h-96 mb-28" >
    <div id="card" class="card-main mb-14 h-64">
      <!-- container for all cards -->
      <%= form_with(model: @book,url: booking_path,class: "meeting-form") do |form| %>
      <div class="container w-100 lg:w-5/5 mx-auto ">
        <!-- card -->
        <div v-for="card in cards" class="flex flex-col md:flex-row overflow-hidden bg-white rounded-lg shadow-xl  justify-center items-center">
          <!-- media -->
          <div class="h-64 md:w-2/4 flex border-r-2 border-gray-50">
            <%= image_tag @car.image.url ,class:"m-8 inset-0 h-3/5 w-1/2"%>
            <div class="w-1/2 mt-16">
              <h3 class="font-semibold text-lg leading-tight truncate "><%= @car.carmakes %>
                <%= @car.carmodels %></h3>
              <h3 class="font-semibold text-lg leading-tight truncate text-right -m-5 mr-3"><%= @car.caryears %></h3><br>
              <p class="text-xs text-gray-500 uppercase tracking-wide  mt-2 mt-10">or similar car from the category</p>
            </div>
          </div>
          <!-- content -->
          <div class="md:w-1/4 py-4 px-6 text-gray-800 flex flex-col mt-14 border-r-2 border-gray-50 justify-center items-center">
            <img src="" alt="">
            <img src="https://image.shutterstock.com/image-vector/car-rental-logo-260nw-737602525.jpg" class="m-8 inset-0 h-5/5 w-2/4">
          </div>
          <div class="md:w-1/4 py-4 px-6 text-gray-800 flex flex-col justify-center items-center">
            <h3 class="font-semibold text-lg leading-tight truncate">$<%= @car.price %>
              <small class="text-xs text-gray-500"> /per day</small>
            </h3>
          </div>
        </div>
        <%= form.hidden_field :price, value: @car.price %>
        <%= form.hidden_field :name, value:@car.user.id  %>
        <%= form.hidden_field :number, value: @totalDays %>
        <%= form.hidden_field :car_id, value:@car.id %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :stripe_payment_id%>
        <%= form.hidden_field :status,value: "paid" %>
        <%= form.hidden_field :dateFrom,value: @from %>
        <%= form.hidden_field :dateTo,value: @to %>
        <%= form.hidden_field :totalPrice,value: @totalPrice %>
        <div v-for="card in cards" class="flex flex-col md:flex-row overflow-hidden bg-white rounded-lg shadow-xl  justify-center items-center">
          <!-- media -->
          <div class="h-64 md:w-2/4 flex border-r-2 border-gray-50  justify-start items-center">
            <div class="w-2/2 mt-16">

            </div>
          </div>
          <!-- content -->
          <div class="md:w-1/4  text-gray-800 flex flex-col  border-r-2 border-gray-50 justify-center ml-6 ">
            <h3 class="text-sm text-gray-900 leading-tight truncate text-left flex mb-2"><%= image_tag ("car1.png") ,class:"w-4 h-4 text-gray-400 mr-2" %> <%= @car.user.companyname %> </h3>
            <h3 class="text-sm text-gray-900 leading-tight truncate text-left flex mb-2"><%= image_tag ("place.png") ,class:"w-4 h-4 text-gray-400 mr-2" %> <%= @car.user.country_cont %>, <%= @car.user.state_cont %>, <%= @car.user.address %> </h3>
            <h3 class="text-sm text-gray-900 leading-tight truncate text-left flex mb-2"><%= image_tag ("phone-call.png") ,class:"w-4 h-4 text-gray-400 mr-2" %> <%= @car.user.phone %> </h3>
          </div>
          <div class="md:w-1/4 py-4 px-6 text-gray-800 flex flex-col justify-center items-center">
            <h3 class="font-semibold text-lg leading-tight truncate">
              <br><%= @totalDays  %>
              <small class="text-xs text-gray-500"> /Days </small><br>
              $<%= @totalPrice %>
              <small class="text-xs text-gray-500">/Total </small>
            </h3>

            <%= form.submit "Check out",class:"mt-4 group relative w-2/4 flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
            focus:ring-indigo-500" %>
          </div>
        </div>
        <div id="cards">
        </div>
        <% end %>
        <!--/ card-->
      </div>
    </div>
  </div>
</div>
<%= render 'footer' %>
<script charset="utf-8">
  var stripe = Stripe('<%= Rails.application.credentials[:stripe][:public]%>');
  // load the fonts in
 var fonts = [{
   cssSrc: "https://fonts.googleapis.com/css?family=Karla",
 }];
 // styles for the stripe inputs
 var styles = {
   base: {
     iconColor: "#4f46e5",
     color: "#4f46e5",
     fontFamily: "MonumentGroteskTrial-Regular",
     fontSize: "16px",


     "::placeholder": {
       color: "#4f46e5"
     },
     ":-webkit-autofill": {
       color: "#4f46e5"
     }
   },
   invalid: {
     iconColor: "#FFC7EE",
     color: "#A31621"
   }
 }

 var elements = stripe.elements();
  var cardElement = elements.create('card', {style: styles});
  cardElement.mount('#cards');
  const form = document.querySelector('#new_submission');
    form.addEventListener('submit', function(e) {
      e.preventDefault();
      // Step 1: POST request to create payment intent
      fetch('/booking', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          authenticity_token: '<%= form_authenticity_token %>',
        }),
      })
      .then((response) => response.json())
      .then((paymentIntent) => {
        // Step 2: Create payment method and confirm payment intent.
        stripe.confirmCardPayment(
          paymentIntent.client_secret, {
            payment_method: {
              card: cardElement
            }
          }
        ).then((resp) => {
          if(resp.error) {
            alert(resp.error.message);
          } else {
            // Step 3: Embed payment ID in form
            const paymentIdInput = document.querySelector('#payment');
            paymentIdInput.value = paymentIntent.id;
            form.submit();
          }
        })
      })
      .catch((error) => {
        console.error('Error:', error);
      });
    });

</script>

app/views/home/index.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="relative bg-white overflow-hidden">
  <div class="max-w-7xl mx-auto ">
    <%= render 'header' %>
    <div class="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28">
      <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-44">
        <div class="sm:text-center lg:text-left">
          <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block text-indigo-600 xl:inline">Find your drive</span>
          </h1>
          <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
            Explore the world's largest car sharing marketplace
          </p>
        </div>
      </main>
    </div>
  </div>
  <div class="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
    <!-- This example requires Tailwind CSS v2.0+ This example requires some changes to your config: ``` // tailwind.config.js module.exports = { // ... plugins: [ // ... require('@tailwindcss/forms'), ], } ``` -->
    <div class="background min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div class=" max-w-md w-full space-y-8">
        <%= search_form_for @search, url: search_path do |f| %>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="my-5">
              <h2 class="h2 mt-6 text-center text-3xl font-extrabold text-gray-900">
                Find a car to rent
              </h2>
            </div>
            <div class="grid grid-cols-12 gap-6">
              <div class="col-span-12 sm:col-span-12 w-4/4">
                <div class="shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline ">
                  <%= f.select :country_cont, options_for_select([:country_cont] ,{class: 'inline-block shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}) %>
                </div>
                <div class="mt-2 shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline ">
                  <%= f.select :state_cont, options_for_select([:state_cont]) ,class:"inline-block shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"%>

                </div>
                <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                  <%= f.submit "Search", class:"group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
                  focus:ring-indigo-500" %>
                  <span class="absolute left-0 inset-y-0 flex items-center pl-3"></span </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'featuer' %>
<%= render 'footer' %>

app/views/home/search.html.erb
<%= render 'header' %>
<div class="container mx-auto mt-5">
  <%= search_form_for @search, url: search_path do |f| %>
  <%= f.text_field :carmakes_cont ,class:"shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-1/6",placeholder:"Maker" %>
  <%= f.text_field :carmodels_cont ,class:"shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-1/6",placeholder:"Model" %>
  <%= f.text_field :caryears_cont ,class:"shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-1/6",placeholder:"Year" %>
  <%= date_field_tag :from ,params[:from],value: Time.now.strftime('%Y-%m-%d') ,class:"shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-1/6"%>
  <%= date_field_tag :to ,params[:to],value: Time.now.strftime('%Y-%m-%d') ,class:"shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-1/6"%>
  <%= submit_tag "Search", class:"mt-4 group relative w-1/7 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500" %>
  <h1></h1>
<% end %>
  </div>
<div class="overflow-auto h-96 mt-9">
  <%  @searchs.each do |car| %>
      <%= form_tag(book_path(dateform: params[:from],dateto: params[:to],id: car.id,price: car.price)) do |f| %>
      <div id="card" class="card-main mb-14">
      <!-- container for all cards -->
      <div class="container w-100 lg:w-5/5 mx-auto flex flex-col">
        <!-- card -->
        <div v-for="card in cards" class="flex flex-col md:flex-row overflow-hidden bg-white rounded-lg shadow-xl  justify-center items-center">
          <!-- media -->
          <div class="h-64 md:w-2/4 flex border-r-2 border-gray-50">
            <%= image_tag car.image.url ,class:"m-8 inset-0 h-3/5 w-1/2"%>
            <div class="w-1/2 mt-16">
              <h3 class="font-semibold text-lg leading-tight truncate "><%= car.carmakes %>
                <%= car.carmodels %></h3>
              <h3 class="font-semibold text-lg leading-tight truncate text-right -m-5 mr-3"><%= car.caryears %></h3><br>
              <p class="text-xs text-gray-500 uppercase tracking-wide  mt-2 mt-10">or similar car from the category</p>
            </div>
          </div>

          <!-- content -->
          <div class="md:w-1/4 py-4 px-6 text-gray-800 flex flex-col mt-14 border-r-2 border-gray-50 justify-center items-center">
            <img src="" alt="">
            <img src="https://image.shutterstock.com/image-vector/car-rental-logo-260nw-737602525.jpg" class="m-8 inset-0 h-5/5 w-2/4">
          </div>
          <div class="md:w-1/4 py-4 px-6 text-gray-800 flex flex-col justify-center items-center">
            <h3 class="font-semibold text-lg leading-tight truncate">$<%= car.price %>
              <small class="text-xs text-gray-500">
                /per day</small>
            </h3>
            <%= submit_tag "Book", class:"mt-4 group relative w-2/4 flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
            focus:ring-indigo-500" %>
          </div>
        </div>
        <!--/ card-->
      </div>
    </div>
  <% end %>
  <% end %>

</div>



<%= render 'footer' %>