config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'
  resources :cars
  resources :werbhooks ,only: [:create]

  get 'business/index', as: :business
  devise_for :users
  devise_for :clients, path: 'clients'
  get 'search' => 'home#search', as: :search
  post'book'=>'home#book',as: :book
  post 'booking'=>'home#create', as: :booking
  get 'invoice'=>'profile#invoice', as: :invoice
  get 'customer'=>'customer#index', as: :customer
  get 'states'=>'home#index'




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/car.rb
class Car < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :books

  after_create do
    @car = Stripe::Product.create(name: carmakes)
    @price = Stripe::Price.create(product: car,unit_amount: self.price, currency: 'usd')
    update(stripe_product_id:  car.id)
  end


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :restrict, only: %i[index show edit update destroy]

  # GET /cars or /cars.json
  def index
    @car = Car.where(user_id: current_client.id)
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
    @array_of_caryears = ['2021']
    @array_of_carmakes = ['Audi']
    @array_of_carmodels = ['233']
    @user = current_client.id
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:carmakes, :carmodels, :image, :caryears, :user_id, :image_cache,:price,:stripe_product_id)
    end

    def restrict
    if @current_user == current_client
      authenticate_client!
    elsif @current_user == current_user
      root_path
    end
  end


end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<div class="flex h-screen overflow-y-hidden bg-white" x-data="setup()" x-init="$refs.loading.classList.add('hidden')">
    <div x-ref="loading" class="fixed inset-0 z-50 flex items-center justify-center text-white bg-black bg-opacity-50" style="backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px)">
      Loading.....
    </div>
    <%= render 'business/sidebar'%>
    <div class="flex flex-col flex-1 h-full overflow-hidden">
      <!-- Navbar -->
      <%= render 'business/header'%>
      <div>
        <div class="flex  justify-center items-center">
          <div class="mt-5 md:mt-0 md:col-span-2">
            <%= form_with(model: car) do |form| %>
            <% if car.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(car.errors.count, "error") %>
                  prohibited this car from being saved:</h2>

                <ul>
                  <% car.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                <div class="car-information flex w-full ">
                  <div class="col-span-6">
                    <%= form.label "Years" %>
                    <%= form.select :caryears, options_for_select([true, false]),class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-5/5 shadow-sm sm:text-sm border-gray-300 rounded-md mr-5" %>
                  </div>
                  <div class="col-span-6">
                    <%= form.label "Maker" %>
                    <%= form.select :carmakes, options_for_select([true, false]),class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-5/5 shadow-sm sm:text-sm border-gray-300 rounded-md mr-5" %>
                  </div>
                  <div class="col-span-6">
                    <%= form.label "Model" %>
                    <%= form.select :carmodels, options_for_select([true, false]),class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-5/5 shadow-sm sm:text-sm border-gray-300 rounded-md " %>
                  </div>
                </div>
                <div class="car-information flex w-full ">
                  <%= form.file_field :image %>
                  <%= form.hidden_field :image_cache %>
                  <%= form.hidden_field :user_id, value: @user %>
                    <%= form.hidden_field :stripe_product_id %>
                  <div class="col-span-6">
                    <%= form.label "Price" %>
                    <%= form.text_field :price ,class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-5/5 shadow-sm sm:text-sm border-gray-300 rounded-md " %>
                  </div>
                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                <button
                  type="submit"
                  class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Save
                </button>
              </div>
            </div>

          </div>
        </div>
      </div>
    <% end %>
  </div>
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" defer="defer"></script>
  <script type="text/javascript" src="http://www.carqueryapi.com/js/jquery.min.js"></script>
  <script type="text/javascript" src="http://www.carqueryapi.com/js/carquery.0.3.4.js"></script>
  <script>
    const setup = () => {
      return {
        loading: true,
        isSidebarOpen: false,
        toggleSidbarMenu() {
          this.isSidebarOpen = !this.isSidebarOpen
        },
        isSettingsPanelOpen: false,
        isSearchBoxOpen: false
      }
    }
  </script>
</div>

app/views/cars/_search_car.html.erb
<div class="p-4 transition-shadow border rounded-lg shadow-sm hover:shadow-lg">
  <div class="flex items-start justify-between">
    <div class="flex flex-col space-y-2">
      <span class="text-gray-400"></span>
      <span class="text-lg font-semibold"><%= car.carmakes %></span>
    </div>
    <%= image_tag car.image.url ,class:" bg-gray-200 rounded-md", style:"width: 8rem;height:8rem" %>
  </div>
  <div>
    <span class="inline-block px-2 text-sm text-white bg-green-300 rounded"><%= car.caryears %></span>
    <span><%= car.carmodels %></span>
  </div>
</div>

app/views/cars/edit.html.erb
<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<!-- component -->
<div>

    <div class="flex h-screen overflow-y-hidden bg-white" x-data="setup()" x-init="$refs.loading.classList.add('hidden')">
       <div
        x-ref="loading"
        class="fixed inset-0 z-50 flex items-center justify-center text-white bg-black bg-opacity-50"
        style="backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px)"
      >
        Loading.....
      </div>
     <%= render 'business/sidebar'%>
      <div class="flex flex-col flex-1 h-full overflow-hidden">
        <!-- Navbar -->
        <%= render 'business/header'%>
        <!-- Main content -->
        <main class="flex-1 max-h-full p-5 overflow-hidden overflow-y-scroll">
          <!-- Main content header -->
          <div
            class="flex flex-col items-start justify-between pb-6 space-y-4 border-b lg:items-center lg:space-y-0 lg:flex-row"
          >
            <h1 class="text-2xl font-semibold whitespace-nowrap">Cars</h1><%= link_to 'New Car', new_car_path ,class:"items:left focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600 focus:bg-indigo-800 focus:outline-none w-full sm:w-auto bg-indigo-700 transition duration-150 ease-in-out hover:bg-indigo-600 rounded text-white px-8 py-3 text-sm mt-6" %>

          </div>
          <p id="notice"><%= notice %></p>
          <!-- Start Content -->
          <div class="grid grid-cols-1 gap-5 mt-6 sm:grid-cols-2 lg:grid-cols-4">
            <% @car.each do |car| %>
                <%= link_to car_path(car.id) do %>
              <div class="p-4 transition-shadow border rounded-lg shadow-sm hover:shadow-lg">
                <div class="flex items-start justify-between">
                  <div class="flex flex-col space-y-2">
                    <span class="text-gray-400"><%= car.carmakes %></span>
                    <span class="text-lg font-semibold"><%= car.carmodels %></span>
                  </div>
                  <%= image_tag car.image.url ,class:" bg-gray-200 rounded-md", style:"width: 8rem;height:8rem" %>
                </div>
                <div>

                  <span class="inline-block px-2 text-sm text-white bg-green-300 rounded"><%= car.caryears %></span>

                  <span>$<%= car.price %></span>
                </div>
              </div>
              <% end %>
              <% end %>
          </div>
        </main>
        <!-- Main footer -->
        <footer class="flex items-center justify-between flex-shrink-0 p-4 border-t max-h-14">
          <div>K-WD &copy; 2021</div>
          <div class="text-sm">
            Made by batis

          </div>

        </footer>
      </div>

      <!-- Setting panel button -->
      <div>
        <button
          @click="isSettingsPanelOpen = true"
          class="fixed right-0 px-4 py-2 text-sm font-medium text-white uppercase transform rotate-90 translate-x-8 bg-gray-600 top-1/2 rounded-b-md"
        >
          Settings
        </button>
      </div>

      <!-- Settings panel -->
      <div
        x-show="isSettingsPanelOpen"
        @click.away="isSettingsPanelOpen = false"
        x-transition:enter="transition transform duration-300"
        x-transition:enter-start="translate-x-full opacity-30  ease-in"
        x-transition:enter-end="translate-x-0 opacity-100 ease-out"
        x-transition:leave="transition transform duration-300"
        x-transition:leave-start="translate-x-0 opacity-100 ease-out"
        x-transition:leave-end="translate-x-full opacity-0 ease-in"
        class="fixed inset-y-0 right-0 flex flex-col bg-white shadow-lg bg-opacity-20 w-80"
        style="backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px)"
      >
        <div class="flex items-center justify-between flex-shrink-0 p-2">
          <h6 class="p-2 text-lg">Settings</h6>
          <button @click="isSettingsPanelOpen = false" class="p-2 rounded-md focus:outline-none focus:ring">
            <svg
              class="w-6 h-6 text-gray-600"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="flex-1 max-h-full p-4 overflow-hidden hover:overflow-y-scroll">
          <span>Settings Content</span>
          <!-- Settings Panel Content ... -->
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" defer></script>
    <script>
      const setup = () => {
        return {
          loading: true,
          isSidebarOpen: false,
          toggleSidbarMenu() {
            this.isSidebarOpen = !this.isSidebarOpen
          },
          isSettingsPanelOpen: false,
          isSearchBoxOpen: false,
        }
      }
    </script>
</div>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>
<!--
  This example requires Tailwind CSS v2.0+ 
  
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
-->

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.carmakes %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.carmodels %>
</p>

<p>
  <strong>Image:</strong>
  <%= @car.image %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @car.caryears %>
</p>

<p>
  <strong>User:</strong>
  <%= @car.user_id %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>